//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.GamesData
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class GamesData { }
#else

	public class GamesData : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public GamesData()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/TGSK_Sketch.Screens;component/SampleData/GamesData/GamesData.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private ItemCollection _Collection = new ItemCollection();

		public ItemCollection Collection
		{
			get
			{
				return this._Collection;
			}
		}
	}

	public class Item : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _GameName = string.Empty;

		public string GameName
		{
			get
			{
				return this._GameName;
			}

			set
			{
				if (this._GameName != value)
				{
					this._GameName = value;
					this.OnPropertyChanged("GameName");
				}
			}
		}

		private string _DateStart = string.Empty;

		public string DateStart
		{
			get
			{
				return this._DateStart;
			}

			set
			{
				if (this._DateStart != value)
				{
					this._DateStart = value;
					this.OnPropertyChanged("DateStart");
				}
			}
		}

		private string _DateEdit = string.Empty;

		public string DateEdit
		{
			get
			{
				return this._DateEdit;
			}

			set
			{
				if (this._DateEdit != value)
				{
					this._DateEdit = value;
					this.OnPropertyChanged("DateEdit");
				}
			}
		}

		private System.Windows.Media.ImageSource _GameIcon = null;

		public System.Windows.Media.ImageSource GameIcon
		{
			get
			{
				return this._GameIcon;
			}

			set
			{
				if (this._GameIcon != value)
				{
					this._GameIcon = value;
					this.OnPropertyChanged("GameIcon");
				}
			}
		}
	}

	public class ItemCollection : System.Collections.ObjectModel.ObservableCollection<Item>
	{ 
	}
#endif
}
